# Generated by Django 4.1.1 on 2023-01-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_previewphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewphoto',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
