# Generated by Django 4.1.1 on 2023-01-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_previewphoto_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
