# Generated by Django 4.1.1 on 2022-10-17 21:09

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalues',
            name='value_float',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[shop.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='attributevalues',
            name='value_int',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attributevalues',
            name='value_text',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='img/<django.db.models.fields.related.ForeignKey>'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[shop.validators.validate_positive]),
        ),
    ]
