# Generated by Django 4.1.1 on 2022-10-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_photo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['time_create']},
        ),
        migrations.AlterField(
            model_name='photo',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
