# Generated by Django 4.1.1 on 2022-10-22 23:59

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalues',
            name='value_float',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, validators=[shop.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='attributevalues',
            name='value_int',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attributevalues',
            name='value_text',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
