# Generated by Django 4.1.1 on 2022-10-23 00:00

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_attributevalues_value_float_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalues',
            name='value_float',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[shop.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='attributevalues',
            name='value_int',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
