# Generated by Django 4.1.1 on 2022-10-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_attributevalues_value_float_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalues',
            name='value_float',
        ),
        migrations.RemoveField(
            model_name='attributevalues',
            name='value_int',
        ),
        migrations.AlterField(
            model_name='attributevalues',
            name='value_text',
            field=models.CharField(default=' ', max_length=128),
        ),
    ]
