# Generated by Django 4.1.1 on 2022-10-23 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_attributevalues_value_float_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='type',
        ),
    ]
