# Generated by Django 4.1.1 on 2022-12-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
    ]
