# Generated by Django 4.1.1 on 2022-12-24 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_order_review_orderlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderList',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
