# Generated by Django 4.1.1 on 2022-12-24 23:35

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_order_review_orderlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[shop.validators.validate_positive]),
        ),
    ]
