# Generated by Django 4.1.1 on 2022-12-25 09:32

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='star_rating',
            field=models.PositiveSmallIntegerField(default=1, validators=[shop.validators.starValid]),
        ),
    ]
