# Generated by Django 4.1.1 on 2022-12-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_review_name_alter_review_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributevalues',
            old_name='attribute_id',
            new_name='attribute',
        ),
        migrations.RenameField(
            model_name='attributevalues',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
