# Generated by Django 4.1.1 on 2022-12-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_rename_attribute_id_attributevalues_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=255),
        ),
    ]
