# Generated by Django 4.1.1 on 2022-12-26 18:02

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[shop.validators.validate_positive]),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
