# Generated by Django 4.1.1 on 2022-12-27 11:41

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_orderlist_price_orderlist_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('sale_percent', models.PositiveSmallIntegerField(validators=[shop.validators.sale_validate])),
                ('max_uses', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderList',
        ),
    ]
