# Generated by Django 4.1.1 on 2022-12-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_order_orderlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderList',
        ),
    ]
