# Generated by Django 4.1.1 on 2022-12-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_order_orderlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
