# Generated by Django 4.1.1 on 2022-12-27 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0041_remove_orderlist_order_remove_orderlist_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New', 'New'), ('In processing', 'In processing'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='New', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[shop.validators.validate_positive])),
                ('payment', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('postcode', models.PositiveSmallIntegerField()),
                ('town', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('order_notes', models.TextField(blank=True)),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.coupon')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[shop.validators.validate_positive])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
        ),
    ]
