# Generated by Django 4.1.1 on 2022-12-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_order_shipping_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
