# Generated by Django 4.1.1 on 2022-12-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_profile_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password_token',
            field=models.CharField(max_length=255),
        ),
    ]
