# Generated by Django 4.1.1 on 2022-12-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_alter_profile_auth_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
