# Generated by Django 4.1.1 on 2022-12-30 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_alter_profile_password_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password_token',
        ),
    ]
