# Generated by Django 4.1.1 on 2022-12-30 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
