# Generated by Django 4.1.1 on 2022-12-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_delete_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_json',
            field=models.JSONField(default={}),
        ),
    ]
