# Generated by Django 4.1.1 on 2023-01-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_profile_user_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_json',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
