# Generated by Django 4.1.1 on 2023-01-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_alter_profile_user_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='new_quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
