# Generated by Django 4.1.1 on 2023-01-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_alter_orderlist_new_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
